### ISSUE TITLE
♻️ Refactors and Fixes

### ISSUE THREAD

**Issue by felipebulcao** [RitsuProject/Ritsu#140]
> ✍ **To Do:**
- [x] Re-Organize Folders and Files
- [x] Better Promise and error handling (again)
- [x] Rename some functions
- [ ] Better Prometheus Command Latency handling.
- [ ] Level Handler Refactor (#121)
- [ ] Phin to Axios (#133)
- [x] Use **ms** instaed of parse-duration in Round Config Handler to parse the round duration. (ref: https://github.com/vercel/ms)
- [x] Use consola in the Logger (ref: https://github.com/nuxt-contrib/consola)
- [x] Switch to discord.js-light (#146)
- [ ] Add the rest of the strings that I didn't add these days to sourceLocales.
> ❗ **Fixes**
- [x] Fix Prometheus Server Counter.
- [x] Fix Memory Leak (really urgent)

> Memory Leak Related
- Memory Leak Suspects:
1. updatePrometheusStats function
2. Classes with useless messages function.
3. Bad use of the collector promise in Round Config Handler.

**Comment by felipebulcao** [comment]
- Memory leak probably fixed in: #142 and #145 

I'll be monitoring.

EDIT: The fix helped, but the problem really seems to be the Discord.js cache.

**Comment by felipebulcao** [comment]
Closing because of V3.
